In [1]:
import tensorflow as tf
print("TensorFlow version: {}".format(tf.__version__))
print("Eager execution is: {}".format(tf.executing_eagerly()))
print("Keras version: {}".format(tf.keras.__version__))

TensorFlow version: 2.1.0
Eager execution is: True
Keras version: 2.2.4-tf


Is the code being run on a gpu?

In [3]:
var = tf.Variable([3, 3])

if tf.test.is_gpu_available():
    print('Running on GPU')
    print('GPU #0?')
    print(var.device.endswith('GPU:0'))
else:
    print('Running on CPU')

W0702 16:48:58.858033  8060 deprecation.py:323] From <ipython-input-3-96aa08269762>:3: is_gpu_available (from tensorflow.python.framework.test_util) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.config.list_physical_devices('GPU')` instead.
Running on CPU


In [4]:
print(tf.config.list_physical_devices('GPU'))

[]


# Declaring variables

In [12]:
t2 = tf.Variable([[1, 2, 3], [5, 4, 7], [3, 1, 3]], dtype = tf.int32)

In [14]:
# Assigning new values to a variable
f1 = tf.Variable(89.)
print(f1)

f1.assign(98)
print(f1)

<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=89.0>
<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=98.0>


In [18]:
mol = tf.constant(42, dtype = tf.int64)
print(mol)

tf.Tensor(42, shape=(), dtype=int64)


In [20]:
print(t2)
t3 = tf.reshape(t2, [9])
print(t3)

<tf.Variable 'Variable:0' shape=(3, 3) dtype=int32, numpy=
array([[1, 2, 3],
       [5, 4, 7],
       [3, 1, 3]])>
tf.Tensor([1 2 3 5 4 7 3 1 3], shape=(9,), dtype=int32)


In [21]:
print(tf.rank(t2))
print(tf.rank(t3))

tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor(1, shape=(), dtype=int32)


In [25]:
print(t2[0:2,0])

[1 5]


In [26]:
print(tf.size(input=t2).numpy())

9


In [28]:
print(t2/t2)

tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]], shape=(3, 3), dtype=float64)


In [32]:
t2t = tf.transpose(t2)

In [33]:
print(tf.matmul(t2, t2t))

tf.Tensor(
[[14 34 14]
 [34 90 40]
 [14 40 19]], shape=(3, 3), dtype=int32)


In [36]:
t1 = tf.Variable(42.3, dtype = tf.float32)
i = tf.cast(t1, dtype = tf.int32)
print(t1)
print(i)

<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=42.3>
tf.Tensor(42, shape=(), dtype=int32)


# Ragged tensors

In [42]:
ragged = tf.ragged.constant([[5, 2, 6, 1], [], [4, 3, 2, 1, 5, 6 ,7, 8], [3, 5, 2]])
print(ragged)
print(ragged[0])
print(ragged[1])
print(ragged[2])

<tf.RaggedTensor [[5, 2, 6, 1], [], [4, 3, 2, 1, 5, 6, 7, 8], [3, 5, 2]]>
tf.Tensor([5 2 6 1], shape=(4,), dtype=int32)
tf.Tensor([], shape=(0,), dtype=int32)
tf.Tensor([4 3 2 1 5 6 7 8], shape=(8,), dtype=int32)


In [44]:
x = tf.RaggedTensor.from_row_splits(values=[5, 2, 6, 1, 4, 10, 7, 8, 6, 7], row_splits = [0, 4, 4, 7, 8, 10])
print(x)

<tf.RaggedTensor [[5, 2, 6, 1], [], [4, 10, 7], [8], [6, 7]]>


In [45]:
x = [1, 3, 5, 7, 11]
y = 5
d = tf.math.squared_difference(x, y)
print(d)

tf.Tensor([16  4  0  4 36], shape=(5,), dtype=int32)


In [46]:
tf.reduce_mean(d)
#axis = 0 to reduce rows
#axis = 1 to reduce columns

<tf.Tensor: shape=(), dtype=int32, numpy=12>

In [47]:
tf.random.normal([3, 2, 1], mean = 0, stddev = 1, dtype = tf.float32)

<tf.Tensor: shape=(3, 2, 1), dtype=float32, numpy=
array([[[ 0.6171746 ],
        [ 1.4923018 ]],

       [[-0.3935163 ],
        [-0.15667547]],

       [[-0.2846362 ],
        [-0.10861127]]], dtype=float32)>

In [48]:
tf.random.uniform(shape = [3, 1], minval = 0, maxval = 1, dtype = tf.float32)

<tf.Tensor: shape=(3, 1), dtype=float32, numpy=
array([[0.10573411],
       [0.03444111],
       [0.82348216]], dtype=float32)>

# Keras, a high-level API for TF 2

In [1]:
epochs = 10
batch_size = 32

In [3]:
import tensorflow as tf

In [4]:
mnist = tf.keras.datasets.mnist
(train_x, train_y), (test_x, test_y) = mnist.load_data()

In [5]:
train_x, test_x = tf.cast(train_x/255.0, tf.float32), tf.cast(test_x/255.0, tf.float32)


In [6]:
train_y, test_y = tf.cast(train_y, tf.int64), tf.cast(test_y, tf.int64)

In [7]:
model1 = tf.keras.models.Sequential([tf.keras.layers.Flatten(), tf.keras.layers.Dense(512, activation = tf.nn.relu), tf.keras.layers.Dropout(0.2), tf.keras.layers.Dense(10, activation = tf.nn.softmax)])

In [11]:
model1.summary()

NameError: name 'model' is not defined

In [9]:
optimiser = tf.keras.optimizers.Adam()
model1.compile(optimizer = optimiser, loss = 'sparse_categorical_crossentropy', metrics = ['accuracy'])

In [12]:
model1.fit(train_x, train_y, batch_size = batch_size, epochs = epochs)

Train on 60000 samples
Epoch 1/10
60000/60000 [==============================] - 54s 902us/sample - loss: 0.2195 - accuracy: 0.9351
Epoch 2/10
60000/60000 [==============================] - 44s 739us/sample - loss: 0.0968 - accuracy: 0.9707
Epoch 3/10
60000/60000 [==============================] - 39s 655us/sample - loss: 0.0706 - accuracy: 0.9777
Epoch 4/10
60000/60000 [==============================] - 38s 637us/sample - loss: 0.0531 - accuracy: 0.9826
Epoch 5/10
60000/60000 [==============================] - 38s 638us/sample - loss: 0.0442 - accuracy: 0.9853
Epoch 6/10
60000/60000 [==============================] - 38s 632us/sample - loss: 0.0373 - accuracy: 0.9875
Epoch 7/10
60000/60000 [==============================] - 38s 637us/sample - loss: 0.0304 - accuracy: 0.9896
Epoch 8/10
60000/60000 [==============================] - 42s 697us/sample - loss: 0.0286 - accuracy: 0.9908
Epoch 9/10
60000/60000 [==============================] - 39s 644us/sample - loss: 0.0242 - accuracy: 0.9

In [13]:
model1.evaluate(test_x, test_y)

10000/10000 [==============================] - 3s 333us/sample - loss: 0.0768 - accuracy: 0.9793


[0.07677479264282629, 0.9793]

In [14]:
model1.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
flatten (Flatten)            multiple                  0         
_________________________________________________________________
dense (Dense)                multiple                  401920    
_________________________________________________________________
dropout (Dropout)            multiple                  0         
_________________________________________________________________
dense_1 (Dense)              multiple                  5130      
Total params: 407,050
Trainable params: 407,050
Non-trainable params: 0
_________________________________________________________________


## Creating models with the add method

In [18]:
model2 = tf.keras.models.Sequential()
model2.add(tf.keras.layers.Flatten())
model2.add(tf.keras.layers.Dense(512, activation = 'relu'))
model2.add(tf.keras.layers.Dropout(0.2))
model2.add(tf.keras.layers.Dense(10, activation=tf.nn.softmax))

model2.compile(optimizer = tf.keras.optimizers.Adam(), loss='sparse_categorical_crossentropy', metrics = ['accuracy'])

In [19]:
model2.fit(train_x, train_y, batch_size = 32, epochs = epochs)

Train on 60000 samples
Epoch 1/10
60000/60000 [==============================] - 85s 1ms/sample - loss: 0.2205 - accuracy: 0.9349
Epoch 2/10
60000/60000 [==============================] - 76s 1ms/sample - loss: 0.0954 - accuracy: 0.9710
Epoch 3/10
60000/60000 [==============================] - 57s 952us/sample - loss: 0.0691 - accuracy: 0.9779
Epoch 4/10
60000/60000 [==============================] - 60s 997us/sample - loss: 0.0543 - accuracy: 0.9821
Epoch 5/10
60000/60000 [==============================] - 40s 668us/sample - loss: 0.0436 - accuracy: 0.9859
Epoch 6/10
60000/60000 [==============================] - 37s 614us/sample - loss: 0.0352 - accuracy: 0.9883
Epoch 7/10
60000/60000 [==============================] - 37s 614us/sample - loss: 0.0316 - accuracy: 0.9894
Epoch 8/10
60000/60000 [==============================] - 38s 640us/sample - loss: 0.0269 - accuracy: 0.9913
Epoch 9/10
60000/60000 [==============================] - 39s 645us/sample - loss: 0.0247 - accuracy: 0.9916


In [21]:
model2.evaluate(test_x, test_y)

10000/10000 [==============================] - 4s 355us/sample - loss: 0.0725 - accuracy: 0.9817


[0.07250103500729056, 0.9817]

## Model definition using the functional API

In [26]:
inputs = tf.keras.Input(shape=(28,28))
x = tf.keras.layers.Flatten()(inputs)
x = tf.keras.layers.Dense(512, activation = 'relu', name = 'd1')(x)
x = tf.keras.layers.Dropout(0.2)(x)
predictions = tf.keras.layers.Dense(10, activation = tf.nn.softmax, name = 'd2')(x)

model3 = tf.keras.Model(inputs = inputs, outputs = predictions)

In [27]:
model3.summary()

Model: "model_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_5 (InputLayer)         [(None, 28, 28)]          0         
_________________________________________________________________
flatten_8 (Flatten)          (None, 784)               0         
_________________________________________________________________
d1 (Dense)                   (None, 512)               401920    
_________________________________________________________________
dropout_5 (Dropout)          (None, 512)               0         
_________________________________________________________________
d2 (Dense)                   (None, 10)                5130      
Total params: 407,050
Trainable params: 407,050
Non-trainable params: 0
_________________________________________________________________


In [30]:
optimiser = tf.keras.optimizers.Adam()
model3.compile(optimizer = optimiser, loss = 'sparse_categorical_crossentropy', metrics = ['accuracy'])
model3.fit(train_x, train_y, batch_size = 32, epochs = epochs)

model3.evaluate(test_x, test_y)

Train on 60000 samples
Epoch 1/10
60000/60000 [==============================] - 57s 948us/sample - loss: 0.2203 - accuracy: 0.9350
Epoch 2/10
60000/60000 [==============================] - 38s 630us/sample - loss: 0.0975 - accuracy: 0.9704
Epoch 3/10
60000/60000 [==============================] - 22s 371us/sample - loss: 0.0685 - accuracy: 0.9784
Epoch 4/10
60000/60000 [==============================] - 23s 377us/sample - loss: 0.0522 - accuracy: 0.9834
Epoch 5/10
60000/60000 [==============================] - 23s 378us/sample - loss: 0.0438 - accuracy: 0.9858
Epoch 6/10
60000/60000 [==============================] - 22s 372us/sample - loss: 0.0352 - accuracy: 0.9892
Epoch 7/10
60000/60000 [==============================] - 22s 369us/sample - loss: 0.0312 - accuracy: 0.9898
Epoch 8/10
60000/60000 [==============================] - 22s 367us/sample - loss: 0.0284 - accuracy: 0.9901
Epoch 9/10
60000/60000 [==============================] - 23s 377us/sample - loss: 0.0257 - accuracy: 0.9

[0.07854417262229245, 0.9793]

## Subclassing the Keras model

In [39]:
class MyModel(tf.keras.Model):
    def __init__(self, num_classes=10):
        super(MyModel, self).__init__()
        inputs = tf.keras.Input(shape=(28, 28))
        self.x0 = tf.keras.layers.Flatten()
        self.x1 = tf.keras.layers.Dense(512, activation = 'relu', name = 'd1')
        self.x2 = tf.keras.layers.Dropout(0.2)
        self.predictions = tf.keras.layers.Dense(10, activation = tf.nn.softmax, name = 'd2')

    def call(self, inputs):
        x = self.x0(inputs)
        x = self.x1(x)
        x = self.x2(x)

        return self.predictions(x)

In [40]:
model4 = MyModel()
steps_per_epoch = len(train_x.numpy())//batch_size
print(steps_per_epoch)

1875


In [41]:
model4.compile(optimizer = tf.keras.optimizers.Adam(), loss = 'sparse_categorical_crossentropy', metrics = ['accuracy'])
model4.fit(train_x, train_y, batch_size=batch_size, epochs = epochs)
model4.evaluate(test_x, test_y)

Train on 60000 samples
Epoch 1/10
60000/60000 [==============================] - 56s 936us/sample - loss: 0.2191 - accuracy: 0.9352
Epoch 2/10
60000/60000 [==============================] - 37s 622us/sample - loss: 0.0941 - accuracy: 0.9708
Epoch 3/10
60000/60000 [==============================] - 31s 516us/sample - loss: 0.0686 - accuracy: 0.9781
Epoch 4/10
60000/60000 [==============================] - 34s 559us/sample - loss: 0.0517 - accuracy: 0.9834
Epoch 5/10
60000/60000 [==============================] - 31s 518us/sample - loss: 0.0428 - accuracy: 0.9857
Epoch 6/10
60000/60000 [==============================] - 32s 531us/sample - loss: 0.0368 - accuracy: 0.9878
Epoch 7/10
60000/60000 [==============================] - 31s 523us/sample - loss: 0.0331 - accuracy: 0.9887
Epoch 8/10
60000/60000 [==============================] - 24s 398us/sample - loss: 0.0248 - accuracy: 0.9919
Epoch 9/10
60000/60000 [==============================] - 18s 298us/sample - loss: 0.0244 - accuracy: 0.9

[0.08180836250958273, 0.9794]

## Using data Pipelines

In [43]:
batch_size = 32
buffer_size = 10000

train_dataset = tf.data.Dataset.from_tensor_slices((train_x, train_y)).batch(batch_size).shuffle(buffer_size)

train_dataset = train_dataset.map(lambda x, y: (tf.image.random_flip_left_right(x), y))
train_dataset = train_dataset.repeat()

In [46]:
test_dataset = tf.data.Dataset.from_tensor_slices((test_x, test_y)).batch(batch_size).shuffle(buffer_size)
test_dataset = test_dataset.repeat()

steps_per_epoch = len(train_x)//batch_size
optimiser = tf.keras.optimizers.Adam()
model5.compile(optimizer = optimiser, loss='sparse_categorical_crossentropy', metrics = ['accuracy'])
model5.fit(train_dataset, batch_size=batch_size, epochs=epochs, steps_per_epochs = steps_per_epoch)

NameError: name 'model' is not defined

## Saving and Loading models

In [53]:
model3.save('./model3.h5')

In [54]:
from tensorflow.keras.models import load_model

new_model = load_model('./model3.h5')

In [55]:
# To save the weights only
new_model.save_weights('./model_weights.h5')

new_model.load_weights('./model_weights.h5')

%%latex
$sin(x)/x$
\bo{available datasets : }
boston_housing, cifar10, cifar100, fashion_mnist, imdb, mnist, reuters

In [56]:
tf.keras.datasets.fashion_mnist.load_data()

4423680/4422102 [==============================] - 1s 0us/step


((array([[[0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          ...,
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0]],
  
         [[0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          ...,
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0]],
  
         [[0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          ...,
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0]],
  
         ...,
  
         [[0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          ...,
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0]],
  
         [[0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0